syntax on
filetype plugin indent on
set hidden
set nocompatible
set number
set nowrap
set showmode
set tw=80
set smartcase
set smarttab
set smartindent
set autoindent
set softtabstop=2
set shiftwidth=2
set expandtab
set incsearch
set mouse=a
set history=1000
set nohlsearch
set inccommand=nosplit
set clipboard=unnamed,unnamedplus

autocmd BufWritePre * %s/\s\+$//e
