# The following lines were added by compinstall

autoload -Uz compinit
compinit
# End of lines configured by zsh-newuser-install

autoload -Uz promptinit
promptinit

# Prompt customization
prompt redhat

# Vi bindings
bindkey -v

# Add .local into PATH

export PATH=$PATH:~/.local/bin

# Pyenv setup
eval "$(pyenv init -)"

# Use Nvim By default
alias vim=nvim

alias l=ls

 [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

 # Temporary Setting for z3
 export PATH=$PATH:/Users/manasvi/Projects/evm-semantics/.build/k/k-distribution/target/release/k/bin:/Users/manasvi/Library/Python/2.7/bin

