# The following lines were added by compinstall

autoload -Uz compinit
compinit
# End of lines configured by zsh-newuser-install

autoload -Uz promptinit
promptinit

# Prompt customization
prompt redhat

# Vi bindings
bindkey -v

# Add .local into PATH

export PATH=$PATH:~/.local/bin


# Use Nvim By default
alias vim=nvim
alias v=nvim


alias l=ls
alias g=git

alias maude=/Applications/Maude-2.7.1-osx/maude.darwin64

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh



